- hosts: kids
  tasks:
    # Adding a tap for https://github.com/Homebrew/homebrew-cask-versions
  - name: cask-versions tap
    homebrew_tap:
      name: homebrew/cask-versions
  - name: homebrew
    homebrew:
      name:
        - bash
        - defaultbrowser
        - dockutil
        - git
        - npm
        - pipenv
        - pstree
        - python
        - tree
        - unrar
        - watch
        - wget
      state: latest
  - name: cask
    homebrew_cask:
      name: "{{item}}"
      state: latest
    with_items:
      - atom
      - google-chrome
      - google-backup-and-sync
      - iterm2
      - minecraft
      - pycharm
      - roblox
      - spotify
      - steam
      - vlc
      - whatsapp
  - pip:
      name:
        - pgzero
      state: latest
      executable: pip3

  # Create basic dirs
  - name: src dir
    file: path=~/Desktop/kod state=directory

  - name: dock clean up
    shell: dockutil --remove "{{item}}"
    with_items:
      - Siri
      - Launchpad
      - Safari
      - Mail
      - Kontakter
      - Kalender
      - Påminnelser
      - Kartor
      - Bilder
      - iTunes

  - name: dock additions
    shell: dockutil --find "{{item.name}}" || dockutil --add "{{item.path}}"
    with_items:
      - name: Google Chrome
        path: "/Applications/Google Chrome.app/"
      - name: iTerm
        path: "/Applications/iTerm.app/"
      - name: PyCharm
        path: "/Applications/PyCharm.app/"
      - name: Spotify
        path: "/Applications/Spotify.app/"
      - name: Steam
        path: "/Applications/Steam.app/"

  - name: Chrome as default
    shell: defaultbrowser chrome
