- hosts: kids
  tasks:
    # Adding a tap for https://github.com/Homebrew/homebrew-cask-versions
  - name: cask-versions tap
    homebrew_tap:
      name: homebrew/cask-versions
  - name: homebrew
    homebrew:
      name:
        - bash
        - git
        - npm
        - pipenv
        - pstree
        - python
        - tree
        - unrar
        - watch
        - wget
      state: latest
  - name: cask
    homebrew_cask:
      name: "{{item}}"
      state: latest
    with_items:
      - atom
      - google-chrome
      - google-backup-and-sync
      - iterm2
      - minecraft
      - pycharm
      - roblox
      - spotify
      - steam
      - vlc
      - whatsapp
  - pip:
      name:
        - pgzero
      state: latest
      executable: pip3

  # Create basic dirs
  - name: src dir
    file: path=~/Desktop/kod state=directory
