- hosts: kids
  tasks:
    # Adding a tap for https://github.com/Homebrew/homebrew-cask-versions
  - name: cask-versions tap
    homebrew_tap:
      name: homebrew/cask-versions
  - name: homebrew
    homebrew:
      name:
        - bash
        - defaultbrowser
        - dockutil
        - git
        - npm
        - pipenv
        - pstree
        - python
        - tree
        - unrar
        - watch
        - wget
      state: latest
  - name: cask
    homebrew_cask:
      name: "{{item}}"
      state: latest
    with_items:
      - atom
      - google-chrome
      - google-backup-and-sync
      - iterm2
      - minecraft
      - pycharm
      - roblox
      - spotify
      - steam
      - vlc
      - whatsapp
  - pip:
      name:
        - pgzero
      state: latest
      executable: pip3

  # Create basic dirs
  - name: src dir
    file: path=~/Desktop/kod state=directory

  - name: dock clean up
    shell: dockutil --remove "{{item}}"
    with_items:
      - Siri
      - Launchpad
      - Safari
      - Mail
      - Kontakter
      - Kalender
      - Påminnelser
      - Kartor
      - Bilder
      - iTunes

  - name: dock additions
    shell: dockutil --find "{{item.name}}" || dockutil --add "{{item.path}}"
    with_items:
      - name: Google Chrome
        path: "/Applications/Google Chrome.app/"
      - name: iTerm
        path: "/Applications/iTerm.app/"
      - name: PyCharm
        path: "/Applications/PyCharm.app/"
      - name: Spotify
        path: "/Applications/Spotify.app/"
      - name: Steam
        path: "/Applications/Steam.app/"
      - name: WhatsApp
        path: "/Applications/WhatsApp.app/"

  - name: Chrome as default
    shell: defaultbrowser chrome

  - name: disable transparency in the menu bar and elsewhere
    osx_defaults: domain=com.apple.universalaccess key=reduceTransparency type=bool value=true

  - name: always show scrollbars
    osx_defaults: key=AppleShowScrollBars value=Always

  - name: Expand save panel by default 1
    osx_defaults: key=NSNavPanelExpandedStateForSaveMode type=bool value=true
  - name: Expand save panel by default 2
    osx_defaults: key=NSNavPanelExpandedStateForSaveMode2 type=bool value=true

  - name: Expand print panel by default 1
    osx_defaults: key=PMPrintingExpandedStateForPrint type=bool value=true
  - name: Expand print panel by default 2
    osx_defaults: key=PMPrintingExpandedStateForPrint2 type=bool value=true

  - name: Save to disk (not to iCloud) by default
    osx_defaults: key=NSDocumentSaveNewDocumentsToCloud type=bool value=false

  - name: Automatically quit printer app once the print jobs complete
    osx_defaults: domain=com.apple.print.PrintingPrefs key="Quit When Finished" type=bool value=true

  - name: Disable the “Are you sure you want to open this application?” dialog
    osx_defaults: domain=com.apple.LaunchServices key=LSQuarantine type=bool value=false

  # Finder
  - name: Finder - new windows open on Desktop 1
    osx_defaults: domain=com.apple.finder key=NewWindowTarget value=PfDe
  - name: Finder - new windows open on Desktop 2
    osx_defaults: domain=com.apple.finder key=NewWindowTargetPath value="file://${HOME}/Desktop/"

  - name: Finder - disable window animations and Get Info animations
    osx_defaults: domain=com.apple.finder key=DisableAllAnimations type=bool value=true

  - name: Finder - show hidden files by default
    osx_defaults: domain=com.apple.finder key=AppleShowAllFiles type=bool value=true

  - name: Finder - hide recent tags
    osx_defaults: domain=com.apple.finder key=ShowRecentTags type=bool value=false

  - name: Finder - show status bar
    osx_defaults: domain=com.apple.finder key=ShowStatusBar type=bool value=true

  - name: Finder - show path bar
    osx_defaults: domain=com.apple.finder key=ShowPathbar type=bool value=true

  - name: Finder - Display full POSIX path as Finder window title
    osx_defaults: domain=com.apple.finder key=_FXShowPosixPathInTitle type=bool value=true

  - name: Finder - When performing a search, search the current folder by default
    osx_defaults: domain=com.apple.finder key=FXDefaultSearchScope value=SCcf

  - name: Finder - Disable the warning when changing a file extension
    osx_defaults: domain=com.apple.finder key=FXEnableExtensionChangeWarning type=bool value=false

  - name: Avoid creating .DS_Store files on network
    osx_defaults: domain=com.apple.desktopservices key=DSDontWriteNetworkStores type=bool value=true

  - name: Avoid creating .DS_Store files on USB drives
    osx_defaults: domain=com.apple.desktopservices key=DSDontWriteUSBStores type=bool value=true

  - name: Automatically open a new Finder window when a volume is mounted 1
    osx_defaults: domain=com.apple.frameworks.diskimages key=auto-open-ro-root type=bool value=true

  - name: Automatically open a new Finder window when a volume is mounted 2
    osx_defaults: domain=com.apple.frameworks.diskimages key=auto-open-rw-root type=bool value=true

  - name: Automatically open a new Finder window when a volume is mounted 3
    osx_defaults: domain=com.apple.finder key=OpenWindowForNewRemovableDisk type=bool value=true

  - name: Use list view in all Finder windows by default
    osx_defaults: domain=com.apple.finder key=FXPreferredViewStyle value=Nlsv

  - name: Disable the warning before emptying the Trash
    osx_defaults: domain=com.apple.finder key=WarnOnEmptyTrash type=bool value=false
