- hosts: lotta
  roles:
    - osx-sensible
  tasks:
    # Adding a tap for https://github.com/Homebrew/homebrew-cask-versions
  - name: cask-versions tap
    homebrew_tap:
      name: homebrew/cask-versions
  - name: homebrew
    homebrew:
      name:
        - defaultbrowser
        - dockutil
      state: latest
  - name: cask
    homebrew_cask:
      name: "{{item}}"
      state: latest
    with_items:
      - google-chrome
      - google-backup-and-sync
      - minecraft
      - roblox
      - spotify
      - steam

  - name: dock clean up
    shell: dockutil --remove "{{item}}"
    with_items:
      - Siri
      - Launchpad
      - Mail
      - Kontakter
      - Kalender
      - Påminnelser
      - Kartor
      - Bilder
      - iTunes

  - name: dock additions
    shell: dockutil --find "{{item.name}}" || dockutil --add "{{item.path}}"
    with_items:
      - name: Google Chrome
        path: "/Applications/Google Chrome.app/"
      - name: Minecraft
        path: "/Applications/Minecraft.app/"
      - name: Spotify
        path: "/Applications/Spotify.app/"
      - name: Steam
        path: "/Applications/Steam.app/"

  - name: Chrome as default
    shell: defaultbrowser chrome
