---

  - name: airflow
    homebrew_cask:
      name: airflow
      state: latest
  - name: vlc
    homebrew_cask:
      name: vlc
      state: latest

  - name: Install duti
    homebrew:
      name: duti
      state: latest

  - name: defaults
    shell: duti -s {{ item.id }} .{{ item.extension }} all
    with_items:
      - extension: mp4
        id: org.videolan.vlc
      - extension: mkv
        id: org.videolan.vlc
